// This file is auto-generated by src/integrations/icons/utils/generate-icon-map.mjs.
// Do not edit manually. Run "npm run generate:icons" (or node src/integrations/icons/utils/generate-icon-map.mjs) to regenerate.

import type { IconType } from 'react-icons';
import { FaArrowRightLong, FaArrowsUpDownLeftRight, FaBullseye, FaClockRotateLeft, FaCompass, FaEye, FaFeather, FaFileLines, FaHeadset, FaLayerGroup, FaLifeRing, FaLink, FaPalette, FaPhone, FaRobot, FaRotateLeft, FaScaleBalanced, FaShieldHalved, FaStar, FaUniversalAccess, FaWandMagicSparkles, FaXmark } from 'react-icons/fa6';
import { LuActivity, LuArrowRight, LuBookOpen, LuChevronLeft, LuChevronRight, LuClipboardCheck, LuCloudLightning, LuContact, LuDroplets, LuGlobe, LuHammer, LuHouse, LuImage, LuLayoutGrid, LuMail, LuMapPin, LuPhone, LuPlugZap, LuReceipt, LuSettings, LuSun, LuTriangleAlert } from 'react-icons/lu';

export const iconMap = {
  'fa6:arrow-right-long': FaArrowRightLong,
  'fa6:arrows-up-down-left-right': FaArrowsUpDownLeftRight,
  'fa6:bullseye': FaBullseye,
  'fa6:clock-rotate-left': FaClockRotateLeft,
  'fa6:compass': FaCompass,
  'fa6:eye': FaEye,
  'fa6:feather': FaFeather,
  'fa6:file-lines': FaFileLines,
  'fa6:headset': FaHeadset,
  'fa6:layer-group': FaLayerGroup,
  'fa6:life-ring': FaLifeRing,
  'fa6:link': FaLink,
  'fa6:palette': FaPalette,
  'fa6:phone': FaPhone,
  'fa6:robot': FaRobot,
  'fa6:rotate-left': FaRotateLeft,
  'fa6:scale-balanced': FaScaleBalanced,
  'fa6:shield-halved': FaShieldHalved,
  'fa6:star': FaStar,
  'fa6:universal-access': FaUniversalAccess,
  'fa6:wand-magic-sparkles': FaWandMagicSparkles,
  'fa6:xmark': FaXmark,
  'lu:activity': LuActivity,
  'lu:arrow-right': LuArrowRight,
  'lu:book-open': LuBookOpen,
  'lu:chevron-left': LuChevronLeft,
  'lu:chevron-right': LuChevronRight,
  'lu:clipboard-check': LuClipboardCheck,
  'lu:cloud-lightning': LuCloudLightning,
  'lu:contact': LuContact,
  'lu:droplets': LuDroplets,
  'lu:globe': LuGlobe,
  'lu:hammer': LuHammer,
  'lu:house': LuHouse,
  'lu:image': LuImage,
  'lu:layout-grid': LuLayoutGrid,
  'lu:mail': LuMail,
  'lu:map-pin': LuMapPin,
  'lu:phone': LuPhone,
  'lu:plug-zap': LuPlugZap,
  'lu:receipt': LuReceipt,
  'lu:settings': LuSettings,
  'lu:sun': LuSun,
  'lu:triangle-alert': LuTriangleAlert,
} satisfies Record<string, IconType>;

export type IconKey = keyof typeof iconMap;
